fix: include NumberHelper for price formatting in IBCOS controller
Error: NoMethodError - undefined method 'number_with_precision'

The product was being found successfully (39,445 parts loaded, match found),
but the controller couldn't format the price because it didn't have access
to the number_with_precision helper.

Added: include ActionView::Helpers::NumberHelper

This fixes the 500 error and allows prices to be formatted correctly.